sudo: required

notifications:
  email: false

services:
  - docker

addons:
    ssh_known_hosts:
      - 137.74.44.48
    apt:
        packages:
            - sshpass

language: java

jdk:
 - oraclejdk8

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export IMAGE_NAME=spring-social
  - docker build -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME
  - docker push $DOCKER_USER/$IMAGE_NAME
  - sshpass -p $DEPLOY_PASS ssh -o stricthostkeychecking=no $DEPLOY_USER@$DEPLOY_HOST bash /$IMAGE_NAME/start.sh
