spring:
    profiles:
      active: dev
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
    accessTokenUri: "{baseUrl}/oauth2/authorize"
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris: http://localhost:4200/auth/login,https://web.spring-social.ovh/auth/login,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect